# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: techsnacks-ui - Build/Deploy to Azure Web App

on:
  push:
    branches: ['main']
    paths: ['src/frontend/**', '.github/workflows/techsnacks-ui.yml']

defaults:
  run:
    working-directory: 'src/frontend/techsnacks-ui'

jobs:

  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build
          npm run test -- --watch=false --browsers=ChromeHeadless
      
      - name: Zip artifact for deployment
        run: Compress-Archive . release.zip
                
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: src/frontend/techsnacks-ui/release.zip

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
          
      - name: unzip artifact for deployment
        run: |
          - Expand-Archive release.zip
          - rm release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'techsnacks'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_16345D14CD55458AABCD810754BE1DE2 }}
          package: .
