name: techsnacks-api - PR Check - Build/Deploy to Azure Web App

on:
  pull_request:
    branches: ['main']
    paths: ['src/backend/**', '.github/workflows/techsnacks-api.yml']
  workflow_dispatch:

defaults:
  run:
    working-directory: 'src/backend/techsnacks/TechSnacks.API'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: install dependencies
        run: dotnet restore

      - name: build
        run: dotnet build --no-restore --configuration Release

      - name: test
        run: dotnet test --no-restore --verbosity normal